# docker-compose.yml

version: "3.7"

services:

  frontend:
    build:
      context:  .
      dockerfile: ./frontend/Dockerfile
    depends_on: 
      - backend
    ports:
       - '4200:4200'

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports: 
      - '3000:3000'
    container_name: backend
